/**
 * Central prop catalog. Adding a new PrizePicks category should start here.
 */
const PROP_DEFINITIONS = [
  {
    id: "pass_yds",
    label: "Passing yards",
    short: "PASS YDS",
    category: "passing",
    family: "passing",
    dist: "normal",
    sources: ["player_game.passing.yds", "overview.passing.YDS"],
    methodology: "opportunity_efficiency",
    opportunity: "pass_attempts",
    efficiency: "yards_per_attempt",
    minGames: 3,
    priorSd: 72,
    floor: 0,
    ceil: 650,
    combo: false,
    matchupKeys: ["passYdsAllowed", "ypaAllowed", "compPctAllowed", "passPpa", "passExplosiveness"],
  },
  {
    id: "pass_att",
    label: "Passing attempts",
    short: "PASS ATT",
    category: "passing",
    family: "passing",
    dist: "normal",
    sources: ["player_game.passing.att"],
    methodology: "opportunity",
    opportunity: "pass_attempts",
    efficiency: null,
    minGames: 3,
    priorSd: 8,
    floor: 0,
    ceil: 80,
    combo: false,
    matchupKeys: ["passYdsAllowed", "pace", "passRate"],
  },
  {
    id: "pass_comp",
    label: "Completions",
    short: "COMP",
    category: "passing",
    family: "passing",
    dist: "normal",
    sources: ["player_game.passing.comp"],
    methodology: "opportunity_efficiency",
    opportunity: "pass_attempts",
    efficiency: "completion_pct",
    minGames: 3,
    priorSd: 6,
    floor: 0,
    ceil: 55,
    combo: false,
    matchupKeys: ["compPctAllowed", "passYdsAllowed"],
  },
  {
    id: "pass_td",
    label: "Passing TDs",
    short: "PASS TD",
    category: "passing",
    family: "passing",
    dist: "poisson",
    sources: ["player_game.passing.td"],
    methodology: "rate",
    opportunity: "pass_attempts",
    efficiency: "td_rate",
    minGames: 4,
    priorSd: 1.1,
    floor: 0,
    ceil: 8,
    combo: false,
    matchupKeys: ["passTdAllowed", "passPpa"],
  },
  {
    id: "pass_int",
    label: "Interceptions",
    short: "INT",
    category: "passing",
    family: "passing",
    dist: "poisson",
    sources: ["player_game.passing.int"],
    methodology: "rate",
    opportunity: "pass_attempts",
    efficiency: "int_rate",
    minGames: 4,
    priorSd: 0.7,
    floor: 0,
    ceil: 6,
    combo: false,
    invertMatchup: true,
    matchupKeys: ["intRateForced", "havoc"],
  },
  {
    id: "rush_yds",
    label: "Rushing yards",
    short: "RUSH YDS",
    category: "rushing",
    family: "rushing",
    dist: "normal",
    sources: ["player_game.rushing.yds"],
    methodology: "opportunity_efficiency",
    opportunity: "rush_attempts",
    efficiency: "yards_per_carry",
    minGames: 3,
    priorSd: 42,
    floor: 0,
    ceil: 350,
    combo: false,
    matchupKeys: ["rushYdsAllowed", "ypcAllowed", "rushPpa", "stuffRate"],
  },
  {
    id: "rush_att",
    label: "Rushing attempts",
    short: "RUSH ATT",
    category: "rushing",
    family: "rushing",
    dist: "normal",
    sources: ["player_game.rushing.att"],
    methodology: "opportunity",
    opportunity: "rush_attempts",
    efficiency: null,
    minGames: 3,
    priorSd: 5.5,
    floor: 0,
    ceil: 45,
    combo: false,
    matchupKeys: ["rushYdsAllowed", "pace"],
  },
  {
    id: "rush_td",
    label: "Rushing TDs",
    short: "RUSH TD",
    category: "rushing",
    family: "rushing",
    dist: "poisson",
    sources: ["player_game.rushing.td"],
    methodology: "rate",
    opportunity: "rush_attempts",
    efficiency: "td_share",
    minGames: 4,
    priorSd: 0.7,
    floor: 0,
    ceil: 6,
    combo: false,
    matchupKeys: ["rushTdAllowed", "rushPpa"],
  },
  {
    id: "rec_yds",
    label: "Receiving yards",
    short: "REC YDS",
    category: "receiving",
    family: "receiving",
    dist: "normal",
    sources: ["player_game.receiving.yds"],
    methodology: "opportunity_efficiency",
    opportunity: "receptions",
    efficiency: "yards_per_reception",
    minGames: 3,
    priorSd: 38,
    floor: 0,
    ceil: 300,
    combo: false,
    matchupKeys: ["passYdsAllowed", "passExplosiveness", "compPctAllowed"],
  },
  {
    id: "rec",
    label: "Receptions",
    short: "REC",
    category: "receiving",
    family: "receiving",
    dist: "normal",
    sources: ["player_game.receiving.rec"],
    methodology: "opportunity",
    opportunity: "receptions",
    efficiency: null,
    minGames: 3,
    priorSd: 2.4,
    floor: 0,
    ceil: 20,
    combo: false,
    matchupKeys: ["compPctAllowed", "passYdsAllowed"],
  },
  {
    id: "rec_td",
    label: "Receiving TDs",
    short: "REC TD",
    category: "receiving",
    family: "receiving",
    dist: "poisson",
    sources: ["player_game.receiving.td"],
    methodology: "rate",
    opportunity: "receptions",
    efficiency: "td_share",
    minGames: 4,
    priorSd: 0.55,
    floor: 0,
    ceil: 5,
    combo: false,
    matchupKeys: ["passTdAllowed", "passPpa"],
  },
  {
    id: "rush_rec_yds",
    label: "Rush + receiving yards",
    short: "RUSH+REC",
    category: "combination",
    family: "skill",
    dist: "normal",
    sources: ["player_game.rushing.yds", "player_game.receiving.yds"],
    methodology: "opportunity_efficiency",
    opportunity: "touches",
    efficiency: "yards_per_touch",
    minGames: 3,
    priorSd: 48,
    floor: 0,
    ceil: 400,
    combo: true,
    parts: ["rush_yds", "rec_yds"],
    matchupKeys: ["rushYdsAllowed", "passYdsAllowed"],
  },
  {
    id: "pass_rush_yds",
    label: "Pass + rush yards",
    short: "PASS+RUSH",
    category: "combination",
    family: "qb",
    dist: "normal",
    sources: ["player_game.passing.yds", "player_game.rushing.yds"],
    methodology: "opportunity_efficiency",
    opportunity: "plays",
    efficiency: "yards_per_play",
    minGames: 3,
    priorSd: 78,
    floor: 0,
    ceil: 700,
    combo: true,
    parts: ["pass_yds", "rush_yds"],
    matchupKeys: ["passYdsAllowed", "rushYdsAllowed"],
  },
  {
    id: "total_td",
    label: "Total touchdowns",
    short: "TOT TD",
    category: "combination",
    family: "scoring",
    dist: "poisson",
    sources: ["player_game.passing.td", "player_game.rushing.td", "player_game.receiving.td"],
    methodology: "rate",
    opportunity: "scoring_chances",
    efficiency: "td_rate",
    minGames: 4,
    priorSd: 0.9,
    floor: 0,
    ceil: 8,
    combo: true,
    parts: ["pass_td", "rush_td", "rec_td"],
    matchupKeys: ["passTdAllowed", "rushTdAllowed"],
  },
];

const PROP_BY_ID = Object.fromEntries(PROP_DEFINITIONS.map((d) => [d.id, d]));

const POSITIONS_BY_STAT = {
  pass_yds: ["QB", "ATH"],
  pass_att: ["QB", "ATH"],
  pass_comp: ["QB", "ATH"],
  pass_td: ["QB", "ATH"],
  pass_int: ["QB", "ATH"],
  pass_rush_yds: ["QB", "ATH"],
  rush_yds: ["QB", "RB", "WR", "ATH"],
  rush_att: ["QB", "RB", "WR", "ATH"],
  rush_td: ["QB", "RB", "WR", "ATH"],
  rec_yds: ["WR", "TE", "RB", "ATH"],
  rec: ["WR", "TE", "RB", "ATH"],
  rec_td: ["WR", "TE", "RB", "ATH"],
  rush_rec_yds: ["RB", "WR", "TE", "ATH"],
  total_td: ["QB", "RB", "WR", "TE", "ATH"],
};

for (const d of PROP_DEFINITIONS) {
  d.positions = POSITIONS_BY_STAT[d.id] || ["QB", "RB", "WR", "TE", "ATH"];
}

function canonicalPosition(pos) {
  const p = String(pos || "")
    .toUpperCase()
    .replace(/[^A-Z]/g, "");
  if (!p) return null;
  if (p === "QB") return "QB";
  if (["RB", "FB", "HB", "TB"].includes(p)) return "RB";
  if (["WR", "SLOT"].includes(p)) return "WR";
  if (p === "TE") return "TE";
  if (["ATH", "UT"].includes(p)) return "ATH";
  return p;
}

function statsForPosition(position, catalog = PROP_DEFINITIONS) {
  const pos = canonicalPosition(position);
  const list = catalog || PROP_DEFINITIONS;
  if (!pos) return list.slice();
  const hit = list.filter((d) => (d.positions || []).includes(pos));
  return hit.length ? hit : list.slice();
}

function getPropDef(id) {
  return PROP_BY_ID[String(id || "")] || null;
}

function catalogPublic() {
  return PROP_DEFINITIONS.map((d) => ({
    id: d.id,
    label: d.label,
    short: d.short,
    category: d.category,
    family: d.family,
    combo: Boolean(d.combo),
    positions: d.positions || [],
  }));
}

module.exports = {
  PROP_DEFINITIONS,
  PROP_BY_ID,
  getPropDef,
  catalogPublic,
  canonicalPosition,
  statsForPosition,
  POSITIONS_BY_STAT,
};
