-- Team schedule prediction game (profile-linked picks + per-team leaderboard)
-- Run in Supabase SQL editor after supabase_schema.sql
-- predicted_*alabama_* columns store the selected team's W/L and score (legacy names).

create table if not exists public.bama_schedule_predictions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  season_year integer not null,
  team_school text not null default 'Alabama',
  cfbd_game_id bigint not null,
  week integer,
  opponent_name text not null,
  is_home boolean not null default true,
  predicted_alabama_win boolean not null,
  predicted_alabama_score integer,
  predicted_opponent_score integer,
  is_winner_correct boolean,
  score_error integer,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, team_school, cfbd_game_id, season_year)
);

create index if not exists idx_bama_preds_user_season
  on public.bama_schedule_predictions (user_id, season_year);

create index if not exists idx_bama_preds_game_season
  on public.bama_schedule_predictions (cfbd_game_id, season_year);

create index if not exists idx_bama_preds_season
  on public.bama_schedule_predictions (season_year);

create index if not exists idx_bama_preds_team_season
  on public.bama_schedule_predictions (team_school, season_year);

alter table public.bama_schedule_predictions enable row level security;
