-- CFP bracket predictions (profile-linked, shared, leaderboard)
-- Run in Supabase SQL editor

create table if not exists public.cfp_brackets (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  season_year integer not null,
  teams jsonb not null default '{}'::jsonb,
  slots jsonb not null default '{}'::jsonb,
  picks jsonb not null default '{}'::jsonb,
  champion_name text,
  is_complete boolean not null default false,
  correct_picks integer not null default 0,
  graded_picks integer not null default 0,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, season_year)
);

create index if not exists idx_cfp_brackets_season
  on public.cfp_brackets (season_year, correct_picks desc);

create index if not exists idx_cfp_brackets_user
  on public.cfp_brackets (user_id);

create table if not exists public.cfp_official_results (
  season_year integer primary key,
  results jsonb not null default '{}'::jsonb,
  locked boolean not null default false,
  updated_at timestamptz not null default now()
);

alter table public.cfp_brackets enable row level security;
alter table public.cfp_official_results enable row level security;
