-- Heisman odds board + prediction game
-- Run via migration / Supabase SQL editor

create table if not exists public.heisman_odds_cache (
  season_year integer primary key,
  payload jsonb not null,
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.heisman_picks (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  season_year integer not null,
  player_key text not null,
  player_name text not null,
  team text,
  american_odds_at_pick integer,
  implied_prob_at_pick numeric(8, 5),
  is_locked boolean not null default false,
  locked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, season_year)
);

create index if not exists idx_heisman_picks_season
  on public.heisman_picks (season_year);

create index if not exists idx_heisman_picks_player
  on public.heisman_picks (season_year, player_key);

create table if not exists public.heisman_results (
  season_year integer primary key,
  winner_player_key text not null,
  winner_name text not null,
  set_by bigint references public.users(id) on delete set null,
  set_at timestamptz not null default now()
);

alter table public.heisman_odds_cache enable row level security;
alter table public.heisman_picks enable row level security;
alter table public.heisman_results enable row level security;
