-- Private leagues for weekly picks (invite-code groups).
-- Run in Supabase SQL editor (or apply via migration).

create table if not exists public.leagues (
  id bigint generated by default as identity primary key,
  name text not null,
  owner_user_id bigint not null references public.users(id) on delete cascade,
  invite_code text not null,
  season_year integer not null,
  created_at timestamptz not null default now(),
  unique (invite_code)
);

create index if not exists idx_leagues_owner
  on public.leagues (owner_user_id);

create index if not exists idx_leagues_season
  on public.leagues (season_year);

create table if not exists public.league_members (
  id bigint generated by default as identity primary key,
  league_id bigint not null references public.leagues(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  unique (league_id, user_id)
);

create index if not exists idx_league_members_user
  on public.league_members (user_id);

create index if not exists idx_league_members_league
  on public.league_members (league_id);

alter table public.leagues enable row level security;
alter table public.league_members enable row level security;
