-- Pick reminder emails (run once in Supabase SQL editor)

-- Opt-in default for new accounts (existing rows unchanged)
alter table public.user_settings
  alter column email_notifications set default false;

create table if not exists public.pick_reminder_log (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  week_id bigint not null references public.weeks(id) on delete cascade,
  sent_at timestamptz not null default now(),
  unique (user_id, week_id)
);

create index if not exists idx_pick_reminder_log_week
  on public.pick_reminder_log (week_id);

alter table public.pick_reminder_log enable row level security;
