-- Player / recruit hometown cache for Recruit Map (run on JawsDB / MySQL)
-- Source: CFBD GET /recruiting/players (see player_hometowns_recruiting_migration.sql for upgrades from older roster-only tables)

CREATE TABLE IF NOT EXISTS PlayerHometowns (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cfbd_player_id INT NULL,
  cfbd_recruit_id VARCHAR(64) NOT NULL,
  athlete_id VARCHAR(64) NULL,
  recruit_type VARCHAR(50) NULL,
  player_name VARCHAR(255) NOT NULL,
  committed_to VARCHAR(255) NULL,
  school VARCHAR(255) NULL,
  team VARCHAR(255) NULL COMMENT 'Display: committedTo or school',
  team_school VARCHAR(255) NULL,
  conference VARCHAR(128) NULL,
  season_year INT NOT NULL,
  position VARCHAR(64) NULL,
  hometown_city VARCHAR(128) NULL,
  hometown_state VARCHAR(64) NULL,
  hometown_country VARCHAR(128) NULL,
  hometown_full VARCHAR(512) NULL,
  latitude DECIMAL(10, 7) NULL,
  longitude DECIMAL(11, 7) NULL,
  stars INT NULL,
  rating DECIMAL(10,4) NULL,
  ranking INT NULL,
  source VARCHAR(64) NOT NULL DEFAULT 'cfbd_recruiting_players',
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_recruit_season (season_year, cfbd_recruit_id),
  KEY idx_season_team (season_year, team(64)),
  KEY idx_conference (conference),
  KEY idx_state (hometown_state),
  KEY idx_position (position),
  KEY idx_recruit_type (recruit_type),
  KEY idx_stars (stars),
  KEY idx_latlng (latitude, longitude)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
