-- CFB Power Ratings schema (Supabase / PostgreSQL)
-- Run in the Supabase SQL editor. Safe to re-run (IF NOT EXISTS).
-- Team IDs align with CFBD team ids (same space stored as *_espn_id elsewhere on this site).

create table if not exists public.power_teams (
  team_id bigint primary key,
  name text not null,
  abbreviation text,
  conference text,
  classification text not null default 'fbs',
  logo_url text,
  updated_at timestamptz not null default now()
);

create table if not exists public.power_games (
  game_id bigint primary key,
  season integer not null,
  week integer not null,
  game_date timestamptz,
  home_team_id bigint not null,
  away_team_id bigint not null,
  neutral_site boolean not null default false,
  home_score integer,
  away_score integer,
  completed boolean not null default false,
  overtime boolean,
  conference_game boolean,
  season_type text not null default 'regular',
  home_classification text,
  away_classification text,
  updated_at timestamptz not null default now()
);

create index if not exists power_games_season_week_idx
  on public.power_games (season, week);

create table if not exists public.power_game_stats (
  game_id bigint primary key references public.power_games(game_id) on delete cascade,
  home_off_epa numeric,
  away_off_epa numeric,
  home_def_epa_allowed numeric,
  away_def_epa_allowed numeric,
  home_success_rate numeric,
  away_success_rate numeric,
  home_explosiveness numeric,
  away_explosiveness numeric,
  home_yards_per_play numeric,
  away_yards_per_play numeric,
  home_points_per_drive numeric,
  away_points_per_drive numeric,
  home_turnovers integer,
  away_turnovers integer,
  home_takeaways integer,
  away_takeaways integer,
  home_sacks numeric,
  away_sacks numeric,
  home_havoc numeric,
  away_havoc numeric,
  home_special_teams_epa numeric,
  away_special_teams_epa numeric,
  play_count integer,
  drives integer,
  updated_at timestamptz not null default now()
);

create table if not exists public.power_team_priors (
  team_id bigint not null,
  season integer not null,
  prev_season_power numeric,
  talent_score numeric,
  blue_chip_pct numeric,
  recruiting_score numeric,
  returning_production numeric,
  special_teams_rating numeric,
  primary key (team_id, season)
);

create table if not exists public.power_personnel_adjustments (
  id bigint generated by default as identity primary key,
  team_id bigint not null,
  player_name text,
  position text,
  status text not null default 'out',
  impact_value numeric not null default 0,
  start_date date,
  end_date date,
  source text not null default 'manual',
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists power_personnel_team_active_idx
  on public.power_personnel_adjustments (team_id, active);

-- Weekly snapshots — never overwrite; unique per team/season/week
create table if not exists public.power_team_ratings (
  id bigint generated by default as identity primary key,
  team_id bigint not null,
  season integer not null,
  week integer not null,
  raw_power numeric not null,
  power_score numeric not null,
  offense_rating numeric,
  defense_rating numeric,
  special_teams_rating numeric,
  talent_rating numeric,
  sos_rating numeric,
  ranking integer not null,
  previous_ranking integer,
  wins integer not null default 0,
  losses integer not null default 0,
  uncertainty numeric,
  created_at timestamptz not null default now(),
  unique (team_id, season, week)
);

create index if not exists power_team_ratings_season_week_rank_idx
  on public.power_team_ratings (season, week, ranking);

create table if not exists public.power_model_runs (
  id bigint generated by default as identity primary key,
  season integer not null,
  week integer not null,
  params jsonb,
  solver jsonb,
  team_count integer,
  created_at timestamptz not null default now()
);

alter table public.power_teams enable row level security;
alter table public.power_games enable row level security;
alter table public.power_game_stats enable row level security;
alter table public.power_team_priors enable row level security;
alter table public.power_personnel_adjustments enable row level security;
alter table public.power_team_ratings enable row level security;
alter table public.power_model_runs enable row level security;
