-- Product analytics for 2026 free public beta (no paywall / Stripe).
-- Writes go through Netlify functions (service role). RLS blocks client direct access.

create table if not exists public.product_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  user_id bigint references public.users(id) on delete set null,
  anonymous_session_id text,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint product_events_name_len check (char_length(event_name) between 1 and 64),
  constraint product_events_anon_len check (
    anonymous_session_id is null or char_length(anonymous_session_id) between 8 and 64
  )
);

create index if not exists product_events_created_at_idx
  on public.product_events (created_at desc);

create index if not exists product_events_event_name_idx
  on public.product_events (event_name);

create index if not exists product_events_user_id_idx
  on public.product_events (user_id)
  where user_id is not null;

create index if not exists product_events_anon_idx
  on public.product_events (anonymous_session_id)
  where anonymous_session_id is not null;

create index if not exists product_events_name_created_idx
  on public.product_events (event_name, created_at desc);

alter table public.product_events enable row level security;

-- No policies for anon/authenticated: only service_role (Netlify) can read/write.
revoke all on table public.product_events from anon, authenticated;
grant all on table public.product_events to service_role;

create table if not exists public.beta_feedback (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  category text not null default 'general',
  message text not null,
  page text,
  status text not null default 'new',
  pinned boolean not null default false,
  created_at timestamptz not null default now(),
  constraint beta_feedback_category_check check (
    category in ('bug', 'feature', 'general')
  ),
  constraint beta_feedback_status_check check (
    status in ('new', 'reviewed', 'done')
  ),
  constraint beta_feedback_message_len check (char_length(message) between 1 and 4000)
);

create index if not exists beta_feedback_created_at_idx
  on public.beta_feedback (created_at desc);

create index if not exists beta_feedback_status_idx
  on public.beta_feedback (status);

create index if not exists beta_feedback_pinned_idx
  on public.beta_feedback (pinned desc, created_at desc);

alter table public.beta_feedback enable row level security;

revoke all on table public.beta_feedback from anon, authenticated;
grant all on table public.beta_feedback to service_role;
