-- Prop Lab: cache, saved entries, backtests
-- Run in the Supabase SQL editor. Non-destructive.

create table if not exists public.prop_lab_cfbd_cache (
  cache_key text primary key,
  payload jsonb not null,
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create index if not exists idx_prop_lab_cfbd_cache_expires
  on public.prop_lab_cfbd_cache (expires_at);

alter table public.prop_lab_cfbd_cache enable row level security;

create table if not exists public.prop_lab_entries (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title text not null,
  season_year integer,
  week_number integer,
  model_version text not null,
  entry_snapshot jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_prop_lab_entries_user
  on public.prop_lab_entries (user_id, created_at desc);

alter table public.prop_lab_entries enable row level security;

create table if not exists public.prop_lab_legs (
  id bigint generated by default as identity primary key,
  entry_id bigint not null references public.prop_lab_entries(id) on delete cascade,
  sort_order integer not null default 0,
  player_id text,
  player_name text,
  team text,
  opponent text,
  stat_id text,
  line numeric,
  side text,
  projection_snapshot jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_prop_lab_legs_entry
  on public.prop_lab_legs (entry_id, sort_order);

alter table public.prop_lab_legs enable row level security;

-- Prediction ledger. A row is written when a projection is made (actual/hit
-- null) and filled in once the game is final. See sql/prop_lab_grading.sql.
create table if not exists public.prop_lab_backtests (
  id bigint generated by default as identity primary key,
  season_year integer,
  week_number integer,
  player_id text,
  player_name text,
  team text,
  opponent text,
  stat_id text,
  model_version text not null,
  projection numeric,
  line numeric,
  side text not null default 'more',
  actual numeric,
  p_hit numeric,
  p_hit_uncalibrated numeric,
  calibrator_method text,
  confidence text,
  prop_score numeric,
  sample_games integer,
  spread numeric,
  hit boolean,
  error numeric,
  source text not null default 'backtest',
  graded_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists uq_prop_lab_backtests_prediction
  on public.prop_lab_backtests (
    model_version, season_year, week_number, player_id, stat_id, line, side
  );

create index if not exists idx_prop_lab_backtests_pending
  on public.prop_lab_backtests (season_year, week_number, team)
  where hit is null;

create index if not exists idx_prop_lab_backtests_graded
  on public.prop_lab_backtests (model_version, source)
  where hit is not null;

create index if not exists idx_prop_lab_backtests_model
  on public.prop_lab_backtests (model_version, stat_id, season_year);

alter table public.prop_lab_backtests enable row level security;

-- Short share links for Prop Lab cards (payload lives here, not in the URL).
create table if not exists public.prop_lab_shares (
  id text primary key,
  payload jsonb not null,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz
);

create index if not exists idx_prop_lab_shares_expires
  on public.prop_lab_shares (expires_at);

alter table public.prop_lab_shares enable row level security;
