-- Prop Lab: weekly Best of the Week board (PrizePicks mirror scored by our model)
-- Run in the Supabase SQL editor. Non-destructive.

create table if not exists public.prop_lab_week_picks (
  id bigint generated by default as identity primary key,
  season_year integer not null,
  week_number integer not null,
  scrape_hash text not null default '',
  model_version text not null,
  status text not null default 'partial',
  generated_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  props_total integer not null default 0,
  props_scored integer not null default 0,
  props_supported integer not null default 0,
  cfbd_calls integer not null default 0,
  league_snapshot_cache text,
  legs_json jsonb not null default '[]'::jsonb,
  combos_json jsonb not null default '{}'::jsonb,
  scores_json jsonb not null default '{}'::jsonb,
  meta_json jsonb not null default '{}'::jsonb,
  unique (season_year, week_number, scrape_hash)
);

create index if not exists idx_prop_lab_week_picks_latest
  on public.prop_lab_week_picks (season_year, week_number, updated_at desc);

alter table public.prop_lab_week_picks enable row level security;
