-- Site name suggestions from the 2026 beta navbar form.
-- Writes go through Netlify (service role). RLS blocks client direct access.

create table if not exists public.site_name_suggestions (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  suggested_name text not null,
  note text,
  page text,
  status text not null default 'new',
  created_at timestamptz not null default now(),
  constraint site_name_suggestions_name_len check (char_length(trim(suggested_name)) between 2 and 80),
  constraint site_name_suggestions_note_len check (note is null or char_length(note) <= 500),
  constraint site_name_suggestions_status_check check (
    status in ('new', 'reviewed', 'shortlisted', 'rejected')
  )
);

create index if not exists site_name_suggestions_created_at_idx
  on public.site_name_suggestions (created_at desc);

create index if not exists site_name_suggestions_status_idx
  on public.site_name_suggestions (status);

alter table public.site_name_suggestions enable row level security;

revoke all on table public.site_name_suggestions from anon, authenticated;
grant all on table public.site_name_suggestions to service_role;
