-- CFB schema for Supabase (PostgreSQL)
-- Run this in the Supabase SQL editor (once per project).

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  email text unique not null,
  password_hash text not null,
  display_name text,
  avatar_url text,
  bio text,
  role text not null default 'user',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_profiles (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  favorite_team_espn_id integer,
  favorite_conference text,
  location text,
  total_picks integer not null default 0,
  correct_picks integer not null default 0,
  accuracy numeric(5,2) not null default 0,
  current_streak integer not null default 0,
  best_streak integer not null default 0,
  ranking integer,
  last_pick_date date
);

create table if not exists public.user_settings (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  email_notifications boolean not null default true,
  theme text not null default 'dark',
  notifications_enabled boolean not null default true
);

create table if not exists public.user_activity (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  activity_type text not null,
  activity_data jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.weeks (
  id bigint generated by default as identity primary key,
  week_number integer not null,
  season_year integer not null,
  start_date date,
  end_date date,
  is_completed boolean not null default false,
  created_at timestamptz not null default now(),
  unique (week_number, season_year)
);

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  week_id bigint not null references public.weeks(id) on delete cascade,
  cfbd_game_id bigint,
  game_number integer not null,
  home_team_espn_id integer not null,
  away_team_espn_id integer not null,
  home_team_name text not null,
  away_team_name text not null,
  home_team_logo_url text,
  away_team_logo_url text,
  game_date timestamptz,
  venue text,
  betting_line numeric(5,1),
  is_completed boolean not null default false,
  created_at timestamptz not null default now(),
  unique (week_id, cfbd_game_id)
);

create table if not exists public.game_results (
  id bigint generated by default as identity primary key,
  game_id bigint not null unique references public.games(id) on delete cascade,
  home_team_score integer,
  away_team_score integer,
  winning_team_espn_id integer not null,
  winning_team_name text not null,
  game_finalized_at timestamptz not null default now()
);

create table if not exists public.user_picks (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  game_id bigint not null references public.games(id) on delete cascade,
  week_id bigint not null references public.weeks(id) on delete cascade,
  picked_team_espn_id integer not null,
  picked_team_name text not null,
  is_correct boolean,
  submitted_at timestamptz not null default now(),
  unique (user_id, game_id)
);

create table if not exists public.weekly_user_stats (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  week_id bigint not null references public.weeks(id) on delete cascade,
  total_picks integer not null default 0,
  correct_picks integer not null default 0,
  incorrect_picks integer not null default 0,
  accuracy numeric(5,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, week_id)
);

create table if not exists public.settings (
  id bigint generated by default as identity primary key,
  setting_key text unique not null,
  setting_value text,
  updated_at timestamptz not null default now()
);

create table if not exists public.player_hometowns (
  id bigint generated by default as identity primary key,
  cfbd_player_id bigint,
  cfbd_recruit_id text unique,
  athlete_id text,
  recruit_type text,
  player_name text not null,
  team text,
  committed_to text,
  school text,
  team_school text,
  conference text,
  season_year integer,
  "position" text,
  hometown_city text,
  hometown_state text,
  hometown_country text,
  hometown_full text,
  latitude double precision,
  longitude double precision,
  stars integer,
  rating numeric,
  ranking integer,
  source text,
  updated_at timestamptz not null default now()
);

create index if not exists idx_users_username on public.users (username);
create index if not exists idx_users_email on public.users (email);
create index if not exists idx_weeks_season on public.weeks (season_year, week_number);
create index if not exists idx_games_week on public.games (week_id, game_number);
create index if not exists idx_player_hometowns_year on public.player_hometowns (season_year);
create index if not exists idx_player_hometowns_team on public.player_hometowns (team);
create index if not exists idx_player_hometowns_coords on public.player_hometowns (latitude, longitude);

alter table public.users enable row level security;
alter table public.user_profiles enable row level security;
alter table public.user_settings enable row level security;
alter table public.user_activity enable row level security;
alter table public.weeks enable row level security;
alter table public.games enable row level security;
alter table public.game_results enable row level security;
alter table public.user_picks enable row level security;
alter table public.weekly_user_stats enable row level security;
alter table public.settings enable row level security;
alter table public.player_hometowns enable row level security;
